declare module "*express"
declare module "*mongoose"
declare module "*cors" 
declare module "*bcrypt" 
declare module "*morgan" 
declare module "*jsonwebtoken" 
declare module "*multer" 
declare module "*path" 